name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
      - uses: cachix/cachix-action@v14
        with:
          name: ${{ env.CACHIX_BINARY_CACHE_NAME }}
          extraPullNames: devenv
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix profile install github:cachix/devenv/latest
        name: Install devenv.sh
      - run: devenv shell echo ok
      - run: devenv ci
